import 'package:flutter/cupertino.dart';

class PsValueHolder {
  PsValueHolder(
      {@required this.loginUserId,
      @required this.userIdToVerify,
      @required this.userNameToVerify,
      @required this.userEmailToVerify,
      @required this.userPasswordToVerify,
      @required this.deviceToken,
      @required this.notiSetting,
      @required this.overAllTaxLabel,
      @required this.overAllTaxValue,
      @required this.shippingTaxLabel,
      @required this.shopId,
      @required this.shopName,
      @required this.messenger,
      @required this.whatsApp,
      @required this.phone,
      @required this.minimumOrderAmount,
      @required this.shippingTaxValue,
      @required this.appInfoVersionNo,
      @required this.appInfoForceUpdate,
      @required this.appInfoForceUpdateTitle,
      @required this.appInfoForceUpdateMsg,
      @required this.startDate,
      @required this.endDate,
      @required this.paypalEnabled,
      @required this.stripeEnabled,
      @required this.codEnabled,
      @required this.bankEnabled,
      @required this.publishKey,
      @required this.paystackKey,
      @required this.paystackEnabled,
      @required this.shippingId,
      @required this.standardShippingEnable,
      @required this.zoneShippingEnable,
      @required this.noShippingEnable});
  String loginUserId;
  String userIdToVerify;
  String userNameToVerify;
  String userEmailToVerify;
  String userPasswordToVerify;
  String deviceToken;
  bool notiSetting;
  String overAllTaxLabel;
  String overAllTaxValue;
  String shippingTaxLabel;
  String shopId;
  String shopName;
  String messenger;
  String whatsApp;
  String phone;
  String minimumOrderAmount;
  String shippingTaxValue;
  String appInfoVersionNo;
  bool appInfoForceUpdate;
  String appInfoForceUpdateTitle;
  String appInfoForceUpdateMsg;
  String startDate;
  String endDate;
  String paypalEnabled;
  String stripeEnabled;
  String codEnabled;
  String bankEnabled;
  String publishKey;
  String paystackKey;

  String paystackEnabled;
  String shippingId;
  String standardShippingEnable;
  String zoneShippingEnable;
  String noShippingEnable;
}
