<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit05b28380ad0e04cc5a7ba40fa7b3eddf
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Stripe\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Stripe\\' => 
        array (
            0 => __DIR__ . '/..' . '/stripe/stripe-php/lib',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit05b28380ad0e04cc5a7ba40fa7b3eddf::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit05b28380ad0e04cc5a7ba40fa7b3eddf::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
